server:
  port: 80
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
eureka:
  client:
    service-url:
      defaultZone: https://obscure-gorge-75280.herokuapp.com/eureka